### ISSUE TITLE
Laravel 8.x support

### ISSUE THREAD

**Issue by mohmedr10** [mehradsadeghi/laravel-crud-generator#2]
Hello , you have a nice crud generator , good job sir 👍🏼.
will you add Laravel **8.x** support any soon ?! 
😃

**Comment by mehradsadeghi** [comment]
Hi @mohmedr10 ,
Thanks for your kind words.

Support for Laravel 8.* will be added very soon.

**Comment by mehradsadeghi** [comment]
@mohmedr10 

You can use this package with Laravel 8.x now via the latest released patch (**v0.5.2**). 

If there were any issue, Feel free to add it to this issue or open another issue (if necessary).
