### ISSUE TITLE
Will you ever create a GUI for it?

### ISSUE THREAD

**Issue by Benoit1980** [mehradsadeghi/laravel-crud-generator#3]
Hello,

I checked your tool today, great, will you ever make a GUI extension out of it like infyom did?
The main problem for most is to remember the syntax of everything(too many frameworks out there) like in your demo the "required email unique:users,email" is something a programmer would need to search in the doc and again and again as it is not straight forward to remember.

With a GUI and tick boxes, it eliminates a lot of the searching.

Just feedback for you to keep as I have noticed that since I started to work more with GUI tools in my coding, I gain a huge amount of time(no need to spend time looking for commands).

I did not know where to write this question, you can delete it no worry.

Thanks.

**Comment by mehradsadeghi** [comment]
Hi

Thanks for your feedback. It's a great idea and I'm sure developers can gain a lot from such feature.

I'm busy with different projects at the moment, But I try my best to get to it ASAP.
Meanwhile I greet any PR about this feature.

**Comment by Benoit1980** [comment]
Thank you so much for taking the time to reply 👍 Good luck with your project!
I would have loved to help but I am stuck with 5 projects at the moment, that's why I was looking for a generator to gain some time, working 7 days per week!  :-(

**Comment by mehradsadeghi** [comment]
> Thank you so much for taking the time to reply  Good luck with your project!
> I would have loved to help but I am stuck with 5 projects at the moment, that's why I was looking for a generator to gain some time, working 7 days per week! :-(

Don't forget to take some rest and doing a bit of workout every day. We'are suppose to work in this industry for a long time :)
