### ISSUE TITLE
About Views

### ISSUE THREAD

**Issue by salihonder05** [mehradsadeghi/laravel-crud-generator#5]
Hi. Thanks for this tool, really! This is exactly what I was looking for.

i was try it. But this tool not generated views.
Is there a problem or is this tool not like the picture?

**Comment by mehradsadeghi** [comment]
Hello @salihonder05 
I hope you're doing well and enjoying CRUD Generator.
Generating views was not a part of my plan for this tool, But any PR would be appreciated.
