### ISSUE TITLE
Target class [App\Page] does not exist.

### ISSUE THREAD

**Issue by rafamem** [mehradsadeghi/laravel-crud-generator#6]
In Laravel 7: I ran php artisan make:crud PageController --model=Page --validation and then the following error appeared ...

 A App\Page model does not exist. Do you want to generate it? (yes/no) [yes]:
 > yes

Model created successfully.

   Illuminate\Contracts\Container\BindingResolutionException 

  Target class [App\Page] does not exist.

  at C:\Users\Rafael\projects\cbc-website\vendor\laravel\framework\src\Illuminate\Container\Container.php:811
    807| 
    808|         try {
    809|             $reflector = new ReflectionClass($concrete);
    810|         } catch (ReflectionException $e) {
  > 811|             throw new BindingResolutionException("Target class [$concrete] does not exist.", 0, $e);
    812|         }
    813| 
    814|         // If the type is not instantiable, the developer is attempting to resolve
    815|         // an abstract type such as an Interface or Abstract Class and there is

  1   C:\Users\Rafael\projects\cbc-website\vendor\laravel\framework\src\Illuminate\Container\Container.php:809
      ReflectionException::("Class App\Page does not exist")

  2   C:\Users\Rafael\projects\cbc-website\vendor\laravel\framework\src\Illuminate\Container\Container.php:809
      ReflectionClass::__construct("App\Page")

**Comment by mehradsadeghi** [comment]
Dear @rafamem, Thanks for reporting this isssue.
I fixed it right away. 
Make sure using the latest version (v0.5.4).
Feel free to report any other issue or bug.
