### ISSUE TITLE
Failed to open stream: No such file or directory

### ISSUE THREAD

**Issue by rafamem** [mehradsadeghi/laravel-crud-generator#7]
After update to 0.5.4...

php artisan make:crud PageController --model=Page --validation

   ErrorException 

  include(E:\Users\desarrollo\projects\website\vendor\composer/../../app/Page.php): failed to open stream: No such file or directory

```
  at E:\Users\desarrollo\projects\website\vendor\composer\ClassLoader.php:444
    440|  * Prevents access to $this/self from included files.
    441|  */
    442| function includeFile($file)
    443| {
  > 444|     include $file;
    445| }
    446|
```

  1   E:\Users\desarrollo\projects\website\vendor\composer\ClassLoader.php:444
      include()

  2   E:\Users\desarrollo\projects\website\vendor\composer\ClassLoader.php:322
  include(E:\Users\desarrollo\projects\website\vendor\composer/../../app/Page.php): failed to open stream: No such file or directory

**Comment by mehradsadeghi** [comment]
Dear @rafamem, Please give more details.
What is your exact Laravel version ?
What is your exact PHP version ?

**Comment by rafamem** [comment]
```
"require": {
        "php": "^7.2.5",
        "fideloper/proxy": "^4.2",
        "fruitcake/laravel-cors": "^1.0",
        "guzzlehttp/guzzle": "^6.3",
        "laravel/framework": "^7.0",
        "laravel/tinker": "^2.0",
        "laravel/ui": "2.4"
    },
```

PHP 7.3.23

**Comment by mehradsadeghi** [comment]
Dear @rafamem, I just tested the **v.0.5.4** of crud generator with a brand new Laravel v7.0 in a containerized environment via below docker-composer file:

```yaml
version: "3"

services:
    php:
      image: php:7.3.23-fpm
      container_name: php
      volumes:
        - ./:/app
```  

And everything worked just fine.

Are you sure you've updated the package correctly ?
Are you sure there is no other external reason for this error ?

Please try the package with a brand new Laravel 7.0 and check if the same error still exists.
