### ISSUE TITLE
 Laravel 8.65 issue: The "requests" option does not exist.

### ISSUE THREAD

**Issue by luizcf14** [mehradsadeghi/laravel-crud-generator#9]
Attempting to create the crud i've probabily found new issue:
![image](https://user-images.githubusercontent.com/11324805/143773796-f135fd26-f210-4e55-ad61-0d216a33591c.png)
[Composer.json ]
"require": {
        "php": "^7.3|^8.0",
        "fruitcake/laravel-cors": "^2.0",
        "guzzlehttp/guzzle": "^7.0.1",
        "laravel/framework": "^8.65",
        "laravel/sanctum": "^2.11",
        "laravel/tinker": "^2.5",
        "laravel/ui": "^3.3",
        "mehradsadeghi/laravel-crud-generator": "^0.5.4"

**Comment by luizcf14** [comment]
I solved the problem, the command "option" must be "options" for laravel ^8.65 (ControllerMakeCommand.php:209)

**Comment by mehradsadeghi** [comment]
Hello dear @luizcf14 .
Thanks for your report.

I'd appreciate if you could make a PR for fixing this issue.

**Comment by mehradsadeghi** [comment]
Fixed in [0.5.5](https://github.com/mehradsadeghi/laravel-crud-generator/releases/tag/v0.5.5)
